name: Build Nukkit Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: maven

    - name: Build plugin dengan Maven
      run: mvn -B package --file pom.xml

    - name: Upload Plugin JAR
      uses: actions/upload-artifact@v4
      with:
        name: ContohPlugin
        path: target/*.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ContohPlugin

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
