name: Build Nukkit Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'

    - name: Generate Gradle Wrapper (fallback jika belum ada)
      run: gradle wrapper

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os}}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}

    - name: Memberi permission pada gradlew
      run: chmod +x gradlew

    - name: Build dengan Gradle Wrapper
      run: ./gradlew build

    - name: Upload Plugin JAR
      uses: actions/upload-artifact@v4
      with:
        name: NukkitPlugin
        path: build/libs/*.jar
